# Constants used across the core package and other modules.

# JWT claim keys
CLAIM_SUBJECT = "sub"
CLAIM_TENANT = "tenant"
CLAIM_ROLES = "roles"
CLAIM_PERMISSIONS = "perms"
CLAIM_JTI = "jti"
CLAIM_ISSUER = "iss"
CLAIM_AUDIENCE = "aud"
CLAIM_ISSUED_AT = "iat"
CLAIM_EXPIRATION = "exp"
CLAIM_NOT_BEFORE = "nbf"
CLAIM_DEVICE_ID = "device_id"
CLAIM_DEVICE_NAME = "device_name"
CLAIM_TOKEN_TYPE = "token_type"
CLAIM_ORGANIZATION_ID = "org_id"
CLAIM_SCHOOL_ID = "school_id"
CLAIM_MFA_VERIFIED = "mfa_verified"

# Token types
TOKEN_TYPE_ACCESS = "access"
TOKEN_TYPE_REFRESH = "refresh"

# HTTP header names
HEADER_AUTHORIZATION = "Authorization"
HEADER_TENANT = "X-Tenant-Id"
HEADER_ORGANIZATION = "X-Organization-Id"
HEADER_SCHOOL = "X-School-Id"
HEADER_REQUEST_ID = "X-Request-Id"
HEADER_CORRELATION_ID = "X-Correlation-Id"
HEADER_CSRF_TOKEN = "X-CSRF-Token"
HEADER_USER_AGENT = "User-Agent"
HEADER_FORWARDED_FOR = "X-Forwarded-For"
HEADER_REAL_IP = "X-Real-IP"
HEADER_IDEMPOTENCY_KEY = "X-Idempotency-Key"

# RBAC Roles
ROLE_TEACHER = "teacher"
ROLE_ADVISER = "adviser"
ROLE_COORDINATOR = "coordinator"
ROLE_PRINCIPAL = "principal"
ROLE_SCHOOL_HEAD = "school_head"
ROLE_DIVISION_STAFF = "division_staff"
ROLE_SUPER_ADMIN = "super_admin"

# Permission categories
PERM_STUDENT_READ = "student.read"
PERM_STUDENT_WRITE = "student.write"
PERM_STUDENT_DELETE = "student.delete"
PERM_ATTENDANCE_READ = "attendance.read"
PERM_ATTENDANCE_WRITE = "attendance.write"
PERM_GRADE_READ = "grade.read"
PERM_GRADE_WRITE = "grade.write"
PERM_GRADE_COMPUTE = "grades.compute"
PERM_FORM_READ = "form.read"
PERM_FORM_WRITE = "form.write"
PERM_FORM_GENERATE = "forms.generate"
PERM_REPORT_READ = "report.read"
PERM_REPORT_WRITE = "report.write"
PERM_REPORT_SUBMIT = "reports.submit"
PERM_USER_READ = "user.read"
PERM_USER_WRITE = "user.write"
PERM_USER_DELETE = "user.delete"
PERM_ROLE_READ = "role.read"
PERM_ROLE_WRITE = "role.write"
PERM_AUDIT_READ = "audit.read"
PERM_SETTINGS_READ = "settings.read"
PERM_SETTINGS_WRITE = "settings.write"
PERM_AI_USE = "ai.use"
PERM_FILE_UPLOAD = "file.upload"
PERM_FILE_DELETE = "file.delete"
PERM_MFA_ENABLE = "mfa.enable"
PERM_MFA_DISABLE = "mfa.disable"
PERM_SESSION_REVOKE = "session.revoke"
PERM_TOKEN_REVOKE = "token.revoke"

# Security event types
EVENT_LOGIN_SUCCESS = "login.success"
EVENT_LOGIN_FAILED = "login.failed"
EVENT_LOGOUT = "logout"
EVENT_PASSWORD_CHANGE = "password.change"
EVENT_PASSWORD_RESET = "password.reset"
EVENT_PASSWORD_RESET_REQUEST = "password.reset.request"
EVENT_TOKEN_REFRESH = "token.refresh"
EVENT_TOKEN_REVOKE = "token.revoke"
EVENT_TOKEN_REUSE_DETECTED = "token.reuse.detected"
EVENT_MFA_ENABLED = "mfa.enabled"
EVENT_MFA_DISABLED = "mfa.disabled"
EVENT_MFA_VERIFIED = "mfa.verified"
EVENT_MFA_FAILED = "mfa.failed"
EVENT_PRIVILEGE_ESCALATION_ATTEMPT = "privilege.escalation.attempt"
EVENT_CROSS_TENANT_ACCESS_ATTEMPT = "cross.tenant.access.attempt"
EVENT_RATE_LIMIT_EXCEEDED = "rate.limit.exceeded"
EVENT_SESSION_CREATED = "session.created"
EVENT_SESSION_REVOKED = "session.revoked"
EVENT_GRADE_MODIFIED = "grade.modified"
EVENT_ATTENDANCE_UPDATED = "attendance.updated"
EVENT_FORM_GENERATED = "form.generated"
EVENT_REPORT_SUBMITTED = "report.submitted"
EVENT_AI_USAGE = "ai.usage"
EVENT_AI_PROMPT_INJECTION_DETECTED = "ai.prompt.injection.detected"
EVENT_FILE_UPLOADED = "file.uploaded"
EVENT_FILE_DOWNLOADED = "file.downloaded"
EVENT_FILE_DELETED = "file.deleted"
EVENT_FILE_VALIDATION_FAILED = "file.validation.failed"
EVENT_DATA_EXPORT = "data.export"
EVENT_DATA_DELETION = "data.deletion"
EVENT_CONSENT_GRANTED = "consent.granted"
EVENT_CONSENT_REVOKED = "consent.revoked"

# Rate limit scopes
RATE_LIMIT_SCOPE_PUBLIC = "public"
RATE_LIMIT_SCOPE_AUTHENTICATED = "authenticated"
RATE_LIMIT_SCOPE_AI = "ai"
RATE_LIMIT_SCOPE_LOGIN = "login"

# Audit log actions
AUDIT_ACTION_LOGIN = "LOGIN"
AUDIT_ACTION_LOGOUT = "LOGOUT"
AUDIT_ACTION_CREATE = "CREATE"
AUDIT_ACTION_READ = "READ"
AUDIT_ACTION_UPDATE = "UPDATE"
AUDIT_ACTION_DELETE = "DELETE"
AUDIT_ACTION_EXPORT = "EXPORT"
AUDIT_ACTION_AI_CALL = "AI_CALL"
AUDIT_ACTION_FILE_UPLOAD = "FILE_UPLOAD"
AUDIT_ACTION_FILE_DOWNLOAD = "FILE_DOWNLOAD"

# File validation
MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024  # 10MB

# Password reset
PASSWORD_RESET_TOKEN_EXPIRE_HOURS = 1
PASSWORD_RESET_COOLDOWN_SECONDS = 300

# Session
MAX_SESSIONS_PER_USER = 10
SESSION_IDLE_TIMEOUT_MINUTES = 30

# Encryption
ENCRYPTED_FIELDS = [
    "refresh_token",
    "guardian_contact_number",
    "guardian_email",
    "parent_contact",
    "student_address",
    "emergency_contact",
]

__all__ = [
    "CLAIM_SUBJECT",
    "CLAIM_TENANT",
    "CLAIM_ROLES",
    "CLAIM_PERMISSIONS",
    "CLAIM_JTI",
    "CLAIM_ISSUER",
    "CLAIM_AUDIENCE",
    "CLAIM_ISSUED_AT",
    "CLAIM_EXPIRATION",
    "CLAIM_NOT_BEFORE",
    "CLAIM_DEVICE_ID",
    "CLAIM_DEVICE_NAME",
    "CLAIM_TOKEN_TYPE",
    "CLAIM_ORGANIZATION_ID",
    "CLAIM_SCHOOL_ID",
    "CLAIM_MFA_VERIFIED",
    "TOKEN_TYPE_ACCESS",
    "TOKEN_TYPE_REFRESH",
    "HEADER_AUTHORIZATION",
    "HEADER_TENANT",
    "HEADER_ORGANIZATION",
    "HEADER_SCHOOL",
    "HEADER_REQUEST_ID",
    "HEADER_CORRELATION_ID",
    "HEADER_CSRF_TOKEN",
    "HEADER_USER_AGENT",
    "HEADER_FORWARDED_FOR",
    "HEADER_REAL_IP",
    "HEADER_IDEMPOTENCY_KEY",
    "ROLE_TEACHER",
    "ROLE_ADVISER",
    "ROLE_COORDINATOR",
    "ROLE_PRINCIPAL",
    "ROLE_SCHOOL_HEAD",
    "ROLE_DIVISION_STAFF",
    "ROLE_SUPER_ADMIN",
    "PERM_STUDENT_READ",
    "PERM_STUDENT_WRITE",
    "PERM_STUDENT_DELETE",
    "PERM_ATTENDANCE_READ",
    "PERM_ATTENDANCE_WRITE",
    "PERM_GRADE_READ",
    "PERM_GRADE_WRITE",
    "PERM_GRADE_COMPUTE",
    "PERM_FORM_READ",
    "PERM_FORM_WRITE",
    "PERM_FORM_GENERATE",
    "PERM_REPORT_READ",
    "PERM_REPORT_WRITE",
    "PERM_REPORT_SUBMIT",
    "PERM_USER_READ",
    "PERM_USER_WRITE",
    "PERM_USER_DELETE",
    "PERM_ROLE_READ",
    "PERM_ROLE_WRITE",
    "PERM_AUDIT_READ",
    "PERM_SETTINGS_READ",
    "PERM_SETTINGS_WRITE",
    "PERM_AI_USE",
    "PERM_FILE_UPLOAD",
    "PERM_FILE_DELETE",
    "PERM_MFA_ENABLE",
    "PERM_MFA_DISABLE",
    "PERM_SESSION_REVOKE",
    "PERM_TOKEN_REVOKE",
    "EVENT_LOGIN_SUCCESS",
    "EVENT_LOGIN_FAILED",
    "EVENT_LOGOUT",
    "EVENT_PASSWORD_CHANGE",
    "EVENT_PASSWORD_RESET",
    "EVENT_PASSWORD_RESET_REQUEST",
    "EVENT_TOKEN_REFRESH",
    "EVENT_TOKEN_REVOKE",
    "EVENT_TOKEN_REUSE_DETECTED",
    "EVENT_MFA_ENABLED",
    "EVENT_MFA_DISABLED",
    "EVENT_MFA_VERIFIED",
    "EVENT_MFA_FAILED",
    "EVENT_PRIVILEGE_ESCALATION_ATTEMPT",
    "EVENT_CROSS_TENANT_ACCESS_ATTEMPT",
    "EVENT_RATE_LIMIT_EXCEEDED",
    "EVENT_SESSION_CREATED",
    "EVENT_SESSION_REVOKED",
    "EVENT_GRADE_MODIFIED",
    "EVENT_ATTENDANCE_UPDATED",
    "EVENT_FORM_GENERATED",
    "EVENT_REPORT_SUBMITTED",
    "EVENT_AI_USAGE",
    "EVENT_AI_PROMPT_INJECTION_DETECTED",
    "EVENT_FILE_UPLOADED",
    "EVENT_FILE_DOWNLOADED",
    "EVENT_FILE_DELETED",
    "EVENT_FILE_VALIDATION_FAILED",
    "EVENT_DATA_EXPORT",
    "EVENT_DATA_DELETION",
    "EVENT_CONSENT_GRANTED",
    "EVENT_CONSENT_REVOKED",
    "RATE_LIMIT_SCOPE_PUBLIC",
    "RATE_LIMIT_SCOPE_AUTHENTICATED",
    "RATE_LIMIT_SCOPE_AI",
    "RATE_LIMIT_SCOPE_LOGIN",
    "AUDIT_ACTION_LOGIN",
    "AUDIT_ACTION_LOGOUT",
    "AUDIT_ACTION_CREATE",
    "AUDIT_ACTION_READ",
    "AUDIT_ACTION_UPDATE",
    "AUDIT_ACTION_DELETE",
    "AUDIT_ACTION_EXPORT",
    "AUDIT_ACTION_AI_CALL",
    "AUDIT_ACTION_FILE_UPLOAD",
    "AUDIT_ACTION_FILE_DOWNLOAD",
    "MAX_FILE_SIZE_BYTES",
    "PASSWORD_RESET_TOKEN_EXPIRE_HOURS",
    "PASSWORD_RESET_COOLDOWN_SECONDS",
    "MAX_SESSIONS_PER_USER",
    "SESSION_IDLE_TIMEOUT_MINUTES",
    "ENCRYPTED_FIELDS",
]